### ISSUE TITLE
Discard Two Cards to get One Card

### ISSUE THREAD

**Issue by darklordabc** [fcalife/artifart#10]
Right now discarding has no benefit to it, I think it would be cool if players could get another card after discarding two cards, like recycling. There is no need to have any visual indicator or buffs or counters for this mechanic, players will learn about it eventually.

**Comment by fcalife** [comment]
How would you feel about it being a physical item token? Like e.g. hearthstone dust? At 4 charges, it'd become a booster pack (2 cards).

**Comment by darklordabc** [comment]
Eh sounds convoluted and has the added problem of taking an inventory spot. What is the advantage of this approach?

**Comment by fcalife** [comment]
Having an indicator of what happened, e.g.

"Card Dust"
Discarding a card has left you with some dust. Collect 4 of those to get a booster pack with new cards.

**Comment by fcalife** [comment]
done
