### ISSUE TITLE
Bot Bug and Crashing Investment Ability

### ISSUE THREAD

**Issue by darklordabc** [fcalife/artifart#16]
"By the way there's a bug with he bots where if they try to pick the same hero as is already in the game they don't spawn in and then if you try to use that card that saves all your money and splits it between your teammates it crashes the server"

~ Gab Ezard ~

**Comment by fcalife** [comment]
"And then if you try to use that card that saves all your money and splits it between your teammates it crashes the server"

Unable to reproduce
