### ISSUE TITLE
Gain cards on killing tower or rax

### ISSUE THREAD

**Issue by darklordabc** [fcalife/artifart#17]

**Comment by fcalife** [comment]
I think the rate at which players gain cards is fine currently. Don't think the "card" metagame needs any extra influence to/from the base game itself.

**Comment by darklordabc** [comment]
Is it? You rarely have more than 1 card and there are cards that encourage not pushing, like the bonus health or bonus damage, getting cards from towers will re emphasis pushing and add add another source of cards

**Comment by fcalife** [comment]
reduced card giveaway interval from 45 to 40 seconds, further reduction pending further developments
