### ISSUE TITLE
Show Loading Players at start of game

### ISSUE THREAD

**Issue by darklordabc** [fcalife/artifart#8]
This is just a general improvement that all custom games should have, but most do not. This reveals the players loading in screen that is usually hidden underneath a useless hero pick screen. 
```
// Credits: EarthSalamander #42
		// Hide vanilla pick screen in loading screen
		HidePickScreen()

		function HidePickScreen() {
			if (!Game.GameStateIs(3)) {
				FindDotaHudElement("PreGame").style.opacity = "0";
				$.Schedule(1.0, HidePickScreen)
			}
			else {
				FindDotaHudElement("PreGame").style.opacity = "1";
			}
		}
```

**Comment by darklordabc** [comment]
@fcalife is there a reason we closed this, it's clearly an improvement than the current setup

**Comment by fcalife** [comment]
I closed because I thought it was done lul

**Comment by darklordabc** [comment]
You know what I mean right? During that loading in phase?

**Comment by fcalife** [comment]
yea
