### ISSUE TITLE
Make X on card only appear on mouseover

### ISSUE THREAD

**Issue by darklordabc** [fcalife/artifart#9]
It's subtle, but the X on the cards, especially when they are overlapping with graphics detracts from the overall aesthetic of the game. The X should instead appear when a player mouse overs the card, so we only see the X when its necessary.
![image](https://user-images.githubusercontent.com/16277198/54108071-e246e180-43d2-11e9-9c73-82b05d01742c.png)

**Comment by fcalife** [comment]
done
